[build]
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build"
  publish = "frontend/dist"
  environment = { 
    NODE_VERSION = "18",
    NPM_FLAGS = "--legacy-peer-deps"
  }

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
