[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https: 'unsafe-inline' 'wasm-unsafe-eval';
      connect-src 'self' https: wss:;
      style-src 'self' https: 'unsafe-inline';
      img-src 'self' https: data: blob:;
      font-src 'self' https: data:;
      media-src 'self' https:;
      frame-src 'self' https:;
    """
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
