[build]
  command = """
    cd frontend && 
    npm install --legacy-peer-deps --prefer-offline && 
    npm run build
  """
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --prefer-offline"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'wasm-unsafe-eval' https: blob:;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self';
      connect-src 'self' https: *.somnia.network;
      frame-src 'self';
      worker-src 'self' blob:;
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
