[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' https:;
      connect-src 'self' https://rpc.ankr.com/somnia_testnet wss:;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self' data:;
      frame-src 'self';
      worker-src 'self';
    """
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
