[build]
  # Команда сборки с обработкой ошибок
  command = """
    if [ -d "frontend" ]; then
      cd frontend &&
      echo "Устанавливаем зависимости..." &&
      npm install --legacy-peer-deps --prefer-offline &&
      echo "Запускаем сборку..." &&
      npm run build || exit 1;
    else
      echo "Ошибка: папка frontend не найдена!";
      exit 1;
    fi
  """
  
  # Папка с результатом сборки
  publish = "frontend/dist"

  # Переменные окружения
  [build.environment]
    NODE_VERSION = "18"                          # Фиксируем версию Node.js
    NPM_FLAGS = "--legacy-peer-deps --prefer-offline" # Флаги для npm
    NEXT_TELEMETRY_DISABLED = "1"                # Отключаем телеметрию
    CI = "true"                                  # Режим CI

  # Оптимизация обработки
  [build.processing]
    skip_processing = true                       # Ускоряет деплой

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Базовые security-заголовки
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CSP для Web3 и MetaMask
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'wasm-unsafe-eval' https: blob:;
      connect-src 'self' https: wss: *.somnia.network;
      style-src 'self' 'unsafe-inline' https:;
      img-src 'self' data: https:;
      font-src 'self' https:;
      frame-src 'self' https:;
      worker-src 'self' blob:;
    """

# SPA роутинг
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Кэширование статики
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Для работы MetaMask
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=600"
    Content-Type = "application/json"
