[build]
  base = "frontend"  # Указываем базовую папку
  command = "npm install && npm run build"
  publish = "dist"   # Путь относительно base (frontend/dist)
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
