[build]
  base = "frontend"       # Netlify будет работать из этой папки
  publish = "dist"        # Указываем относительно base directory
  command = "npm install && npm run build"  # Теперь команда выполняется внутри frontend/

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
