[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  base = "./"

[build.environment]
  NODE_VERSION = "20"  # Рекомендуемая версия для Vite 5
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "true"

# Основные редиректы для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Глобальные заголовки безопасности
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https:;
      connect-src *;
      style-src 'self' 'unsafe-inline';
      img-src * data:;
      font-src 'self' data:;
    """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Кэширование для статических assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
