[build]
  command = """
    cd frontend && 
    npm install --legacy-peer-deps --prefer-offline && 
    npm run build
  """
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --prefer-offline"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

    [[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"
