[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "true"

# Редиректы для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Безопасные заголовки с поддержкой Vite/React
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
      connect-src 'self' https:;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self' data:;
      worker-src 'self' blob:;
    """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
