[build]
  base = "frontend"  # Добавьте эту строку!
  command = "npm install && npm run build"
  publish = "dist"   # Упростите путь (без дублирования frontend)
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
