[build]
  command = """
    if [ -d "frontend" ]; then
      cd frontend &&
      echo "Очищаем кэш..." &&
      rm -rf node_modules package-lock.json .npmrc &&
      echo "Устанавливаем зависимости..." &&
      npm install --legacy-peer-deps --prefer-offline &&
      echo "Запускаем сборку..." &&
      npm run build || exit 1;
    else
      echo "Ошибка: папка frontend не найдена!";
      exit 1;
    fi
  """
  
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --prefer-offline"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'wasm-unsafe-eval' https: blob:;
      connect-src 'self' https: wss: *.somnia.network;
      style-src 'self' 'unsafe-inline' https:;
      img-src 'self' data: https:;
      font-src 'self' https:;
      frame-src 'self' https:;
      worker-src 'self' blob:;
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=600"
    Content-Type = "application/json"
