[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "true"

# Редиректы для SPA (чтобы роутинг работал)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Заголовки для безопасности
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https:;
      connect-src *;
      style-src 'self' 'unsafe-inline';
      img-src * data:;
      font-src 'self' data:;
    """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Кэширование статики
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
